if(EXISTS "/home/akdkkras/CLionProjects/BMSTU_matrix/mybuild/BMSTU_matrix_tests[1]_tests.cmake")
  include("/home/akdkkras/CLionProjects/BMSTU_matrix/mybuild/BMSTU_matrix_tests[1]_tests.cmake")
else()
  add_test(BMSTU_matrix_tests_NOT_BUILT BMSTU_matrix_tests_NOT_BUILT)
endif()
